### 1. Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 

In [4]:
import numpy as np
a = np.array([16, 6, 98, 25, 5, 93], dtype=int)
array_shape = a.shape
array_size = a.size
array_boyut = a.ndim

In [5]:
print("Array:", a)
print("Array'ın tipi:", type(a))
print("Array'ın satır ve sütun sayısı (shape):", array_shape)
print("Array'ın eleman sayısı (size):", array_size)
print("Array:", array_boyut)

Array: [16  6 98 25  5 93]
Array'ın tipi: <class 'numpy.ndarray'>
Array'ın satır ve sütun sayısı (shape): (6,)
Array'ın eleman sayısı (size): 6
Array: 1


### 2. İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 

In [6]:
import numpy as np
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [7]:
print("2D Array:\n", array_2d)
print("2D Array boyutu:", array_2d.ndim)
print("2D Array satır ve sütun sayısı (shape):", array_2d.shape)
print("2D Array eleman sayısı (size):", array_2d.size)
print("2D Array satır sayısı:", array_2d.shape[0])
print("2D Array sütun sayısı:", array_2d.shape[1])
print("2D Array 1. satır:", array_2d[0,:])
print("2D Array 2. satır:", array_2d[1,:])
print("2D Array 1. sutun:", array_2d[:,0])
print("2D Array 2. sutun:", array_2d[:,1])

2D Array:
 [[1 2 3]
 [4 5 6]]
2D Array boyutu: 2
2D Array satır ve sütun sayısı (shape): (2, 3)
2D Array eleman sayısı (size): 6
2D Array satır sayısı: 2
2D Array sütun sayısı: 3
2D Array 1. satır: [1 2 3]
2D Array 2. satır: [4 5 6]
2D Array 1. sutun: [1 4]
2D Array 2. sutun: [2 5]


In [8]:
print("3D Array:\n", array_3d)
print("3D Array boyutu:", array_3d.ndim)
print("3D Array satır ve sütun sayısı (shape):", array_3d.shape)
print("3D Array eleman sayısı (size):", array_3d.size)
print("3D Array satır sayısı:", array_3d.shape[0])
print("3D Array sütun sayısı:", array_3d.shape[1])
print("3D Array 1. satır:", array_3d[0,:])
print("3D Array 2. satır:", array_3d[1,:])
print("3D Array 1. sutun:", array_3d[:,0])
print("3D Array 2. sutun:", array_2d[:,1])

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3D Array boyutu: 3
3D Array satır ve sütun sayısı (shape): (2, 2, 2)
3D Array eleman sayısı (size): 8
3D Array satır sayısı: 2
3D Array sütun sayısı: 2
3D Array 1. satır: [[1 2]
 [3 4]]
3D Array 2. satır: [[5 6]
 [7 8]]
3D Array 1. sutun: [[1 2]
 [5 6]]
3D Array 2. sutun: [2 5]


### İki boyutlu array'de tek bir elemana erişim (indexleme)
2D Array:

\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 &6 \end{bmatrix}


In [9]:
array_2d[0, 0]

1

In [10]:
array_2d[1, 2]

6

### İki boyutlu array'de bir dilime erişim (slicing)

In [11]:
array_2d[1,1:]

array([5, 6])

In [12]:
array_2d[:,0:1]

array([[1],
       [4]])

In [13]:
array_2d[:1,1:]

array([[2, 3]])

In [14]:
array_2d[:1,2:]

array([[3]])

In [15]:
array_2d[:,2:]

array([[3],
       [6]])

### Üç boyutlu array'de tek bir elemana erişim (indexleme)

In [22]:
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
array_3d[0, 0, 0]

1

In [24]:
array_3d[0, 1, 1]

4

In [28]:
array_3d[1, 0, 1]

6

### Üç boyutlu array'de bir dilime erişim (slicing)

In [30]:
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [32]:
array_3d[:,0:1,:]

array([[[1, 2]],

       [[5, 6]]])

In [33]:
array_3d[1:,0:1,:]

array([[[5, 6]]])

### 3. Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır 

In [91]:
array_1d = np.arange(1, 5, 1)
boyut = array_1d.ndim
print('Boyut:', boyut)
print('Arange:', array_1d)

Boyut: 1
Arange: [1 2 3 4]


In [92]:
array_2d = np.arange(1, 13, 1)
array_2d.resize(3,4)
boyut = array_1d.ndim
print('Boyut:', boyut)
print('Arange:\n', array_2d)

Boyut: 1
Arange:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [93]:
array_3d = np.arange(1, 61, 1)
array_3d.resize(3,4,5)
boyut = array_3d.ndim
print('Boyut:', boyut)
print('Arange:\n', array_3d)

Boyut: 3
Arange:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


### 1D indexleme ve dilimleme(slicing) işlemi

In [94]:
array_1d

array([1, 2, 3, 4])

In [96]:
array_1d[2]

3

In [97]:
array_1d[2:]

array([3, 4])

### 2D indexleme ve dilimleme(slicing) işlemi
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix}

\begin{bmatrix}
0,0 & 0,1 & 0,2 & 0,3 \\
1,0 & 1,1 & 1,2 & 1,3 \\
2,0 & 2,1 & 2,2 & 2,3
\end{bmatrix}



In [98]:
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
array_2d[1,1]

6

In [100]:
array_2d[2,3]

12

In [101]:
array_2d[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [106]:
array_2d[1:,:2]

array([[ 5,  6],
       [ 9, 10]])

### 3D indexleme ve dilimleme(slicing) işlemi
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & 7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14 & 15 \\
16 & 17 & 18 & 19 & 20
\end{bmatrix} 

\begin{bmatrix}
21 & 22 & 23 & 24 & 25 \\
26 & 27 & 28 & 29 & 30 \\
31 & 32 & 33 & 34 & 35 \\
36 & 37 & 38 & 39 & 40
\end{bmatrix} 

\begin{bmatrix}
41 & 42 & 43 & 44 & 45 \\
46 & 47 & 48 & 49 & 50 \\
51 & 52 & 53 & 54 & 55 \\
56 & 57 & 58 & 59 & 60
\end{bmatrix}

\begin{bmatrix}
0,0,0 & 0,0,1 & 0,0,2 & 0,0,3 & 0,0,4 \\
0,1,0 & 0,1,1 & 0,1,2 & 0,1,3 & 0,1,4 \\
0,2,0 & 0,2,1 & 0,2,2 & 0,2,3 & 0,2,4\\
0,3,0 & 0,3,1 & 0,3,2 & 0,3,3 & 0,3,4
\end{bmatrix} 

\begin{bmatrix}
1,0,0 & 1,0,1 & 1,0,2 & 1,0,3 & 1,0,4 \\
1,1,0 & 1,1,1 & 1,1,2 & 1,1,3 & 1,1,4 \\
1,2,0 & 1,2,1 & 1,2,2 & 1,2,3 & 1,2,4  \\
1,3,0 & 1,3,1 & 1,3,2 & 1,3,3 & 1,3,4 
\end{bmatrix} 

\begin{bmatrix}
2,0,0 & 2,0,1 & 2,0,2 & 2,0,3 & 2,0,4 \\
2,1,0 & 2,1,1 & 2,1,2 & 2,1,3 & 2,1,4 \\
2,2,0 & 2,2,1 & 2,2,2 & 2,2,3 & 2,2,4  \\
2,3,0 & 2,3,1 & 2,3,2 & 2,3,3 & 2,3,4 
\end{bmatrix} 

In [110]:
array_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [135]:
array_3d[2,3,4]

60

In [138]:
array_3d[1:,0:1,:]

array([[[21, 22, 23, 24, 25]],

       [[41, 42, 43, 44, 45]]])

### 4. Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir. 

In [144]:
zero = np.zeros((3,3))
print("Array boyut:\n", zero.ndim)
print("Array:\n", zero)

Array boyut:
 2
Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [145]:
one = np.ones((3,3))
print("Array boyut:\n", one.ndim)
print("Array:\n", one)

Array boyut:
 2
Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [148]:
yatay_birlesim = np.hstack((zero,one))
print('Yatay Birleşim:\n', yatay_birlesim)

Yatay Birleşim:
 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [149]:
dikey_birlesim = np.vstack((zero,one))
print('Dikey Birleşim:\n', dikey_birlesim)

Dikey Birleşim:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
